### ISSUE TITLE
Tons of errors

### ISSUE THREAD

**Issue by ghost** [tm4n/survive-game#1]
I'm getting a load of errors when i try to compile, example 
cannot open include file actor.h: no such file or directory
Everything is where it should be, i also installed new libraries
any ideas?

More errors

`Error	22	error C1083: Cannot open include file: 'actor.h': No such file or directory	c:\users\dom\desktop\survive-game-master\server\collectible.h	4	1	survive_cl_win32
Error	23	error C1083: Cannot open include file: 'actor.h': No such file or directory	c:\users\dom\desktop\survive-game-master\server\box.h	3	1	survive_cl_win32
Error	15	error C1083: Cannot open include file: 'defs.h': No such file or directory	c:\users\dom\desktop\survive-game-master\server\scoremgr.h	4	1	survive_cl_win32
Error	38	error C1083: Cannot open include file: 'defs.h': No such file or directory	c:\users\dom\desktop\survive-game-master\client\backends\b_settings.h	4	1	survive_cl_win32
Error	24	error C1083: Cannot open include file: 'detail/_fixes.hpp': No such file or directory	c:\users\dom\desktop\survive-game-master\client\glm\glm.hpp	81	1	survive_cl_win32
Error	25	error C1083: Cannot open include file: 'detail/_fixes.hpp': No such file or directory	c:\users\dom\desktop\survive-game-master\client\glm\glm.hpp	81	1	survive_cl_win32
Error	26	error C1083: Cannot open include file: 'detail/_fixes.hpp': No such file or directory	c:\users\dom\desktop\survive-game-master\client\glm\glm.hpp	81	1	survive_cl_win32
Error	28	error C1083: Cannot open include file: 'detail/_fixes.hpp': No such file or directory	c:\users\dom\desktop\survive-game-master\client\glm\glm.hpp	81	1	survive_cl_win32
Error	30	error C1083: Cannot open include file: 'detail/_fixes.hpp': No such file or directory	c:\users\dom\desktop\survive-game-master\client\glm\glm.hpp	81	1	survive_cl_win32
Error	33	error C1083: Cannot open include file: 'detail/_fixes.hpp': No such file or directory	c:\users\dom\desktop\survive-game-master\client\glm\glm.hpp	81	1	survive_cl_win32
Error	34	error C1083: Cannot open include file: 'detail/_fixes.hpp': No such file or directory	c:\users\dom\desktop\survive-game-master\client\glm\glm.hpp	81	1	survive_cl_win32
Error	35	error C1083: Cannot open include file: 'detail/_fixes.hpp': No such file or directory	c:\users\dom\desktop\survive-game-master\client\glm\glm.hpp	81	1	survive_cl_win32
Error	36	error C1083: Cannot open include file: 'detail/_fixes.hpp': No such file or directory	c:\users\dom\desktop\survive-game-master\client\glm\glm.hpp	81	1	survive_cl_win32
Error	37	error C1083: Cannot open include file: 'detail/_fixes.hpp': No such file or directory	c:\users\dom\desktop\survive-game-master\client\glm\glm.hpp	81	1	survive_cl_win32
Error	41	error C1083: Cannot open include file: 'detail/_fixes.hpp': No such file or directory	c:\users\dom\desktop\survive-game-master\client\glm\glm.hpp	81	1	survive_cl_win32
Error	42	error C1083: Cannot open include file: 'detail/_fixes.hpp': No such file or directory	c:\users\dom\desktop\survive-game-master\client\glm\glm.hpp	81	1	survive_cl_win32
Error	43	error C1083: Cannot open include file: 'detail/_fixes.hpp': No such file or directory	c:\users\dom\desktop\survive-game-master\client\glm\glm.hpp	81	1	survive_cl_win32
Error	44	error C1083: Cannot open include file: 'detail/_fixes.hpp': No such file or directory	c:\users\dom\desktop\survive-game-master\client\glm\glm.hpp	81	1	survive_cl_win32
Error	45	error C1083: Cannot open include file: 'detail/_fixes.hpp': No such file or directory	c:\users\dom\desktop\survive-game-master\client\glm\glm.hpp	81	1	survive_cl_win32
Error	46	error C1083: Cannot open include file: 'detail/_fixes.hpp': No such file or directory	c:\users\dom\desktop\survive-game-master\client\glm\glm.hpp	81	1	survive_cl_win32
Error	47	error C1083: Cannot open include file: 'detail/_fixes.hpp': No such file or directory	c:\users\dom\desktop\survive-game-master\client\glm\glm.hpp	81	1	survive_cl_win32
Error	8	error C1083: Cannot open include file: 'enet/enet.h': No such file or directory	c:\users\dom\desktop\survive-game-master\shared\game.h	5	1	survive_cl_win32
Error	5	error C1083: Cannot open include file: 'enet/win32.h': No such file or directory	c:\users\dom\desktop\survive-game-master\shared\backends\enet\enet.h	16	1	survive_cl_win32
Error	17	error C1083: Cannot open include file: 'game.h': No such file or directory	c:\users\dom\desktop\survive-game-master\server\gameserver.h	4	1	survive_cl_win32
Error	21	error C1083: Cannot open include file: 'game.h': No such file or directory	c:\users\dom\desktop\survive-game-master\server\gameserver.h	4	1	survive_cl_win32
Error	2	error C1083: Cannot open include file: 'glm/glm.hpp': No such file or directory	c:\users\dom\desktop\survive-game-master\shared\helper.h	6	1	survive_cl_win32
Error	3	error C1083: Cannot open include file: 'glm/glm.hpp': No such file or directory	c:\users\dom\desktop\survive-game-master\shared\helper.h	6	1	survive_cl_win32
Error	6	error C1083: Cannot open include file: 'glm/glm.hpp': No such file or directory	c:\users\dom\desktop\survive-game-master\shared\helper.h	6	1	survive_cl_win32
Error	7	error C1083: Cannot open include file: 'glm/glm.hpp': No such file or directory	c:\users\dom\desktop\survive-game-master\shared\helper.h	6	1	survive_cl_win32
Error	9	error C1083: Cannot open include file: 'glm/glm.hpp': No such file or directory	c:\users\dom\desktop\survive-game-master\shared\helper.h	6	1	survive_cl_win32
Error	12	error C1083: Cannot open include file: 'glm/glm.hpp': No such file or directory	c:\users\dom\desktop\survive-game-master\shared\helper.h	6	1	survive_cl_win32
Error	31	error C1083: Cannot open include file: 'gui_serverlist.h': No such file or directory	c:\users\dom\desktop\survive-game-master\client\gui_serverlist.cpp	1	1	survive_cl_win32
Error	20	error C1083: Cannot open include file: 'level.h': No such file or directory	c:\users\dom\desktop\survive-game-master\server\level_sv.h	4	1	survive_cl_win32
Error	19	error C1083: Cannot open include file: 'net.h': No such file or directory	c:\users\dom\desktop\survive-game-master\server\net_sv.h	4	1	survive_cl_win32
Error	18	error C1083: Cannot open include file: 'npc.h': No such file or directory	c:\users\dom\desktop\survive-game-master\server\npc_sv.h	4	1	survive_cl_win32
Error	16	error C1083: Cannot open include file: 'projectile.h': No such file or directory	c:\users\dom\desktop\survive-game-master\server\projectile_sv.h	4	1	survive_cl_win32
Error	1	error C1083: Cannot open include file: 'ResourceLoader.h': No such file or directory	c:\users\dom\desktop\survive-game-master\shared\backends\b_weapons.h	5	1	survive_cl_win32
Error	4	error C1083: Cannot open include file: 'ResourceLoader.h': No such file or directory	c:\users\dom\desktop\survive-game-master\shared\backends\b_npcs.h	5	1	survive_cl_win32
Error	10	error C1083: Cannot open include file: 'ResourceLoader.h': No such file or directory	c:\users\dom\desktop\survive-game-master\shared\backends\b_weapons.h	5	1	survive_cl_win32
Error	11	error C1083: Cannot open include file: 'ResourceLoader.h': No such file or directory	c:\users\dom\desktop\survive-game-master\shared\backends\b_npcs.h	5	1	survive_cl_win32
Error	13	error C1083: Cannot open include file: 'SDL2/SDL.h': No such file or directory	c:\users\dom\desktop\survive-game-master\shared\timer.cpp	2	1	survive_cl_win32
Error	40	error C1083: Cannot open include file: 'SDL2/SDL_mixer.h': No such file or directory	c:\users\dom\desktop\survive-game-master\client\sound.h	4	1	survive_cl_win32
Error	27	error C1083: Cannot open include file: 'SDL2/SDL_ttf.h': No such file or directory	c:\users\dom\desktop\survive-game-master\client\texture.h	6	1	survive_cl_win32
Error	29	error C1083: Cannot open include file: 'SDL2/SDL_ttf.h': No such file or directory	c:\users\dom\desktop\survive-game-master\client\main.cpp	3	1	survive_cl_win32
Error	32	error C1083: Cannot open include file: 'SDL2/SDL_ttf.h': No such file or directory	c:\users\dom\desktop\survive-game-master\client\texture.h	6	1	survive_cl_win32
Error	39	error C1083: Cannot open include file: 'SDL2/SDL_ttf.h': No such file or directory	c:\users\dom\desktop\survive-game-master\client\texture.h	6	1	survive_cl_win32
Error	48	error C1083: Cannot open include file: 'SDL2/SDL_ttf.h': No such file or directory	c:\users\dom\desktop\survive-game-master\client\texture.h	6	1	survive_cl_win32
Error	49	error C1083: Cannot open include file: 'SDL2/SDL_ttf.h': No such file or directory	c:\users\dom\desktop\survive-game-master\client\texture.h	6	1	survive_cl_win32
Error	50	error C1083: Cannot open include file: 'SDL2/SDL_ttf.h': No such file or directory	c:\users\dom\desktop\survive-game-master\client\texture.h	6	1	survive_cl_win32
Error	51	error C1083: Cannot open include file: 'Texture.h': No such file or directory	c:\users\dom\desktop\survive-game-master\client\cubetexture.h	4	1	survive_cl_win32
Error	14	error C1083: Cannot open include file: 'weaponmgr.h': No such file or directory	c:\users\dom\desktop\survive-game-master\server\weaponmgr_sv.h	4	1	survive_cl_win32
	53	IntelliSense: cannot open source file "detail/func_common.hpp"	c:\Users\Dom\Desktop\survive-game-master\client\glm\common.hpp	35	1	survive_cl_win32
	54	IntelliSense: cannot open source file "detail/func_exponential.hpp"	c:\Users\Dom\Desktop\survive-game-master\client\glm\exponential.hpp	35	1	survive_cl_win32
	56	IntelliSense: cannot open source file "detail/type_float.hpp"	c:\Users\Dom\Desktop\survive-game-master\client\glm\fwd.hpp	36	1	survive_cl_win32
	55	IntelliSense: cannot open source file "detail/type_int.hpp"	c:\Users\Dom\Desktop\survive-game-master\client\glm\fwd.hpp	35	1	survive_cl_win32
	58	IntelliSense: cannot open source file "detail/type_mat.hpp"	c:\Users\Dom\Desktop\survive-game-master\client\glm\fwd.hpp	38	1	survive_cl_win32
	57	IntelliSense: cannot open source file "detail/type_vec.hpp"	c:\Users\Dom\Desktop\survive-game-master\client\glm\fwd.hpp	37	1	survive_cl_win32
	52	IntelliSense: cannot open source file "Texture.h"	c:\Users\Dom\Desktop\survive-game-master\client\CubeTexture.h	4	1	survive_cl_win32
	59	IntelliSense: name followed by '::' must be a class or namespace name	c:\Users\Dom\Desktop\survive-game-master\client\glm\fwd.hpp	129	10	survive_cl_win32
	60	IntelliSense: name followed by '::' must be a class or namespace name	c:\Users\Dom\Desktop\survive-game-master\client\glm\fwd.hpp	133	10	survive_cl_win32
	61	IntelliSense: name followed by '::' must be a class or namespace name	c:\Users\Dom\Desktop\survive-game-master\client\glm\fwd.hpp	137	10	survive_cl_win32
	62	IntelliSense: name followed by '::' must be a class or namespace name	c:\Users\Dom\Desktop\survive-game-master\client\glm\fwd.hpp	141	10	survive_cl_win32
	63	IntelliSense: name followed by '::' must be a class or namespace name	c:\Users\Dom\Desktop\survive-game-master\client\glm\fwd.hpp	145	10	survive_cl_win32
	64	IntelliSense: name followed by '::' must be a class or namespace name	c:\Users\Dom\Desktop\survive-game-master\client\glm\fwd.hpp	149	10	survive_cl_win32
	65	IntelliSense: name followed by '::' must be a class or namespace name	c:\Users\Dom\Desktop\survive-game-master\client\glm\fwd.hpp	153	10	survive_cl_win32
	66	IntelliSense: name followed by '::' must be a class or namespace name	c:\Users\Dom\Desktop\survive-game-master\client\glm\fwd.hpp	157	10	survive_cl_win32
	67	IntelliSense: name followed by '::' must be a class or namespace name	c:\Users\Dom\Desktop\survive-game-master\client\glm\fwd.hpp	161	10	survive_cl_win32
	68	IntelliSense: name followed by '::' must be a class or namespace name	c:\Users\Dom\Desktop\survive-game-master\client\glm\fwd.hpp	165	10	survive_cl_win32
	69	IntelliSense: name followed by '::' must be a class or namespace name	c:\Users\Dom\Desktop\survive-game-master\client\glm\fwd.hpp	169	10	survive_cl_win32
	70	IntelliSense: name followed by '::' must be a class or namespace name	c:\Users\Dom\Desktop\survive-game-master\client\glm\fwd.hpp	173	10	survive_cl_win32
	71	IntelliSense: name followed by '::' must be a class or namespace name	c:\Users\Dom\Desktop\survive-game-master\client\glm\fwd.hpp	177	10	survive_cl_win32
	72	IntelliSense: name followed by '::' must be a class or namespace name	c:\Users\Dom\Desktop\survive-game-master\client\glm\fwd.hpp	181	10	survive_cl_win32
	73	IntelliSense: name followed by '::' must be a class or namespace name	c:\Users\Dom\Desktop\survive-game-master\client\glm\fwd.hpp	185	10	survive_cl_win32
	74	IntelliSense: name followed by '::' must be a class or namespace name	c:\Users\Dom\Desktop\survive-game-master\client\glm\fwd.hpp	189	10	survive_cl_win32
	75	IntelliSense: name followed by '::' must be a class or namespace name	c:\Users\Dom\Desktop\survive-game-master\client\glm\fwd.hpp	193	10	survive_cl_win32
	76	IntelliSense: name followed by '::' must be a class or namespace name	c:\Users\Dom\Desktop\survive-game-master\client\glm\fwd.hpp	197	10	survive_cl_win32
	77	IntelliSense: name followed by '::' must be a class or namespace name	c:\Users\Dom\Desktop\survive-game-master\client\glm\fwd.hpp	201	10	survive_cl_win32
	78	IntelliSense: name followed by '::' must be a class or namespace name	c:\Users\Dom\Desktop\survive-game-master\client\glm\fwd.hpp	205	10	survive_cl_win32
	79	IntelliSense: name followed by '::' must be a class or namespace name	c:\Users\Dom\Desktop\survive-game-master\client\glm\fwd.hpp	209	10	survive_cl_win32
	80	IntelliSense: name followed by '::' must be a class or namespace name	c:\Users\Dom\Desktop\survive-game-master\client\glm\fwd.hpp	213	10	survive_cl_win32
	81	IntelliSense: name followed by '::' must be a class or namespace name	c:\Users\Dom\Desktop\survive-game-master\client\glm\fwd.hpp	217	10	survive_cl_win32
	82	IntelliSense: name followed by '::' must be a class or namespace name	c:\Users\Dom\Desktop\survive-game-master\client\glm\fwd.hpp	221	10	survive_cl_win32
	83	IntelliSense: name followed by '::' must be a class or namespace name	c:\Users\Dom\Desktop\survive-game-master\client\glm\fwd.hpp	225	10	survive_cl_win32
	84	IntelliSense: name followed by '::' must be a class or namespace name	c:\Users\Dom\Desktop\survive-game-master\client\glm\fwd.hpp	229	10	survive_cl_win32
	85	IntelliSense: name followed by '::' must be a class or namespace name	c:\Users\Dom\Desktop\survive-game-master\client\glm\fwd.hpp	233	10	survive_cl_win32
	86	IntelliSense: name followed by '::' must be a class or namespace name	c:\Users\Dom\Desktop\survive-game-master\client\glm\fwd.hpp	237	10	survive_cl_win32
	87	IntelliSense: name followed by '::' must be a class or namespace name	c:\Users\Dom\Desktop\survive-game-master\client\glm\fwd.hpp	241	10	survive_cl_win32
	88	IntelliSense: name followed by '::' must be a class or namespace name	c:\Users\Dom\Desktop\survive-game-master\client\glm\fwd.hpp	245	10	survive_cl_win32
	89	IntelliSense: name followed by '::' must be a class or namespace name	c:\Users\Dom\Desktop\survive-game-master\client\glm\fwd.hpp	249	10	survive_cl_win32
	90	IntelliSense: name followed by '::' must be a class or namespace name	c:\Users\Dom\Desktop\survive-game-master\client\glm\fwd.hpp	253	10	survive_cl_win32
	91	IntelliSense: name followed by '::' must be a class or namespace name	c:\Users\Dom\Desktop\survive-game-master\client\glm\fwd.hpp	257	10	survive_cl_win32
	92	IntelliSense: name followed by '::' must be a class or namespace name	c:\Users\Dom\Desktop\survive-game-master\client\glm\fwd.hpp	261	10	survive_cl_win32
	93	IntelliSense: name followed by '::' must be a class or namespace name	c:\Users\Dom\Desktop\survive-game-master\client\glm\fwd.hpp	265	10	survive_cl_win32
	94	IntelliSense: name followed by '::' must be a class or namespace name	c:\Users\Dom\Desktop\survive-game-master\client\glm\fwd.hpp	269	10	survive_cl_win32
	95	IntelliSense: name followed by '::' must be a class or namespace name	c:\Users\Dom\Desktop\survive-game-master\client\glm\fwd.hpp	274	10	survive_cl_win32
	96	IntelliSense: name followed by '::' must be a class or namespace name	c:\Users\Dom\Desktop\survive-game-master\client\glm\fwd.hpp	278	10	survive_cl_win32
	97	IntelliSense: name followed by '::' must be a class or namespace name	c:\Users\Dom\Desktop\survive-game-master\client\glm\fwd.hpp	282	10	survive_cl_win32
	98	IntelliSense: name followed by '::' must be a class or namespace name	c:\Users\Dom\Desktop\survive-game-master\client\glm\fwd.hpp	286	10	survive_cl_win32
	99	IntelliSense: name followed by '::' must be a class or namespace name	c:\Users\Dom\Desktop\survive-game-master\client\glm\fwd.hpp	297	10	survive_cl_win32
	100	IntelliSense: name followed by '::' must be a class or namespace name	c:\Users\Dom\Desktop\survive-game-master\client\glm\fwd.hpp	301	10	survive_cl_win32
	101	IntelliSense: name followed by '::' must be a class or namespace name	c:\Users\Dom\Desktop\survive-game-master\client\glm\fwd.hpp	305	10	survive_cl_win32
	102	IntelliSense: name followed by '::' must be a class or namespace name	c:\Users\Dom\Desktop\survive-game-master\client\glm\fwd.hpp	309	10	survive_cl_win32
	103	IntelliSense: name followed by '::' must be a class or namespace name	c:\Users\Dom\Desktop\survive-game-master\client\glm\fwd.hpp	314	10	survive_cl_win32
	104	IntelliSense: name followed by '::' must be a class or namespace name	c:\Users\Dom\Desktop\survive-game-master\client\glm\fwd.hpp	318	10	survive_cl_win32
	105	IntelliSense: name followed by '::' must be a class or namespace name	c:\Users\Dom\Desktop\survive-game-master\client\glm\fwd.hpp	322	10	survive_cl_win32
	106	IntelliSense: name followed by '::' must be a class or namespace name	c:\Users\Dom\Desktop\survive-game-master\client\glm\fwd.hpp	326	10	survive_cl_win32
	107	IntelliSense: tvec1 is not a template	c:\Users\Dom\Desktop\survive-game-master\client\glm\fwd.hpp	332	10	survive_cl_win32
	111	IntelliSense: tvec1 is not a template	c:\Users\Dom\Desktop\survive-game-master\client\glm\fwd.hpp	349	10	survive_cl_win32
	115	IntelliSense: tvec1 is not a template	c:\Users\Dom\Desktop\survive-game-master\client\glm\fwd.hpp	366	10	survive_cl_win32
	119	IntelliSense: tvec1 is not a template	c:\Users\Dom\Desktop\survive-game-master\client\glm\fwd.hpp	411	10	survive_cl_win32
	123	IntelliSense: tvec1 is not a template	c:\Users\Dom\Desktop\survive-game-master\client\glm\fwd.hpp	428	10	survive_cl_win32
	127	IntelliSense: tvec1 is not a template	c:\Users\Dom\Desktop\survive-game-master\client\glm\fwd.hpp	445	10	survive_cl_win32
	131	IntelliSense: tvec1 is not a template	c:\Users\Dom\Desktop\survive-game-master\client\glm\fwd.hpp	491	10	survive_cl_win32
	135	IntelliSense: tvec1 is not a template	c:\Users\Dom\Desktop\survive-game-master\client\glm\fwd.hpp	508	10	survive_cl_win32
	139	IntelliSense: tvec1 is not a template	c:\Users\Dom\Desktop\survive-game-master\client\glm\fwd.hpp	525	10	survive_cl_win32
	143	IntelliSense: tvec1 is not a template	c:\Users\Dom\Desktop\survive-game-master\client\glm\fwd.hpp	570	10	survive_cl_win32
	147	IntelliSense: tvec1 is not a template	c:\Users\Dom\Desktop\survive-game-master\client\glm\fwd.hpp	587	10	survive_cl_win32
	151	IntelliSense: tvec1 is not a template	c:\Users\Dom\Desktop\survive-game-master\client\glm\fwd.hpp	604	10	survive_cl_win32
	108	IntelliSense: tvec2 is not a template	c:\Users\Dom\Desktop\survive-game-master\client\glm\fwd.hpp	336	10	survive_cl_win32
	112	IntelliSense: tvec2 is not a template	c:\Users\Dom\Desktop\survive-game-master\client\glm\fwd.hpp	353	10	survive_cl_win32
	116	IntelliSense: tvec2 is not a template	c:\Users\Dom\Desktop\survive-game-master\client\glm\fwd.hpp	370	10	survive_cl_win32
	120	IntelliSense: tvec2 is not a template	c:\Users\Dom\Desktop\survive-game-master\client\glm\fwd.hpp	415	10	survive_cl_win32
	124	IntelliSense: tvec2 is not a template	c:\Users\Dom\Desktop\survive-game-master\client\glm\fwd.hpp	432	10	survive_cl_win32
	128	IntelliSense: tvec2 is not a template	c:\Users\Dom\Desktop\survive-game-master\client\glm\fwd.hpp	449	10	survive_cl_win32
	132	IntelliSense: tvec2 is not a template	c:\Users\Dom\Desktop\survive-game-master\client\glm\fwd.hpp	495	10	survive_cl_win32
	136	IntelliSense: tvec2 is not a template	c:\Users\Dom\Desktop\survive-game-master\client\glm\fwd.hpp	512	10	survive_cl_win32
	140	IntelliSense: tvec2 is not a template	c:\Users\Dom\Desktop\survive-game-master\client\glm\fwd.hpp	529	10	survive_cl_win32
	144	IntelliSense: tvec2 is not a template	c:\Users\Dom\Desktop\survive-game-master\client\glm\fwd.hpp	574	10	survive_cl_win32
	148	IntelliSense: tvec2 is not a template	c:\Users\Dom\Desktop\survive-game-master\client\glm\fwd.hpp	591	10	survive_cl_win32
	109	IntelliSense: tvec3 is not a template	c:\Users\Dom\Desktop\survive-game-master\client\glm\fwd.hpp	340	10	survive_cl_win32
	113	IntelliSense: tvec3 is not a template	c:\Users\Dom\Desktop\survive-game-master\client\glm\fwd.hpp	357	10	survive_cl_win32
	117	IntelliSense: tvec3 is not a template	c:\Users\Dom\Desktop\survive-game-master\client\glm\fwd.hpp	374	10	survive_cl_win32
	121	IntelliSense: tvec3 is not a template	c:\Users\Dom\Desktop\survive-game-master\client\glm\fwd.hpp	419	10	survive_cl_win32
	125	IntelliSense: tvec3 is not a template	c:\Users\Dom\Desktop\survive-game-master\client\glm\fwd.hpp	436	10	survive_cl_win32
	129	IntelliSense: tvec3 is not a template	c:\Users\Dom\Desktop\survive-game-master\client\glm\fwd.hpp	453	10	survive_cl_win32
	133	IntelliSense: tvec3 is not a template	c:\Users\Dom\Desktop\survive-game-master\client\glm\fwd.hpp	499	10	survive_cl_win32
	137	IntelliSense: tvec3 is not a template	c:\Users\Dom\Desktop\survive-game-master\client\glm\fwd.hpp	516	10	survive_cl_win32
	141	IntelliSense: tvec3 is not a template	c:\Users\Dom\Desktop\survive-game-master\client\glm\fwd.hpp	533	10	survive_cl_win32
	145	IntelliSense: tvec3 is not a template	c:\Users\Dom\Desktop\survive-game-master\client\glm\fwd.hpp	578	10	survive_cl_win32
	149	IntelliSense: tvec3 is not a template	c:\Users\Dom\Desktop\survive-game-master\client\glm\fwd.hpp	595	10	survive_cl_win32
	110	IntelliSense: tvec4 is not a template	c:\Users\Dom\Desktop\survive-game-master\client\glm\fwd.hpp	344	10	survive_cl_win32
	114	IntelliSense: tvec4 is not a template	c:\Users\Dom\Desktop\survive-game-master\client\glm\fwd.hpp	361	10	survive_cl_win32
	118	IntelliSense: tvec4 is not a template	c:\Users\Dom\Desktop\survive-game-master\client\glm\fwd.hpp	378	10	survive_cl_win32
	122	IntelliSense: tvec4 is not a template	c:\Users\Dom\Desktop\survive-game-master\client\glm\fwd.hpp	423	10	survive_cl_win32
	126	IntelliSense: tvec4 is not a template	c:\Users\Dom\Desktop\survive-game-master\client\glm\fwd.hpp	440	10	survive_cl_win32
	130	IntelliSense: tvec4 is not a template	c:\Users\Dom\Desktop\survive-game-master\client\glm\fwd.hpp	457	10	survive_cl_win32
	134	IntelliSense: tvec4 is not a template	c:\Users\Dom\Desktop\survive-game-master\client\glm\fwd.hpp	503	10	survive_cl_win32
	138	IntelliSense: tvec4 is not a template	c:\Users\Dom\Desktop\survive-game-master\client\glm\fwd.hpp	520	10	survive_cl_win32
	142	IntelliSense: tvec4 is not a template	c:\Users\Dom\Desktop\survive-game-master\client\glm\fwd.hpp	537	10	survive_cl_win32
	146	IntelliSense: tvec4 is not a template	c:\Users\Dom\Desktop\survive-game-master\client\glm\fwd.hpp	582	10	survive_cl_win32
	150	IntelliSense: tvec4 is not a template	c:\Users\Dom\Desktop\survive-game-master\client\glm\fwd.hpp	599	10	survive_cl_win32
`

**Comment by tm4n** [comment]
This probably happens because of hard coded paths in the visual studio project. I will need to change those to relative paths. It'll take a while until I find the time to do that. You can also do it yourself for testing, the settings are in the project properties.

**Comment by ghost** [comment]
Alright, fixed. but there are even more errors than before now.
Anyway, in what program were the models made?

Errors: https://pastebin.com/ERXPUFyi

**Comment by tm4n** [comment]
Hm these errors don't help, there must be more specific errors above. What version of visual studio are you using? I'm still on 2013.
The models are in the mdl5 format from the "3D Game Studio". I first started the game with this engine, and the format is easy to parse. If you download a trial version, the Model editor (med.exe) can open the files. When saving, you need to use "Save as" and select the MDL5 format.

**Comment by ghost** [comment]
Im using Visual Studio Express 2013.
v120 xp tools
aslo there are no more errors because the printer says that error count exceed 100 and stops compiling and i only have this logs

**Comment by ghost** [comment]
so, any fix? 😢

**Comment by tm4n** [comment]
I've changed the visual studio project a bit. Please get the new version from github and work through what I added to the library README.md file. That information was missing before. If you still get errors after that, please cancel the build after the first errors show up. That way you should be able to copy the first errors that are displayed.

**Comment by ghost** [comment]
Ok thank you. Issue is fixed, now compiles without any errors.
